messages:
    Prefix: ''
    Header: ''
    Footer: ''
    Note: '&fЩоб очистити всі скарги -  пропишіть &e/reports clear&f.'
    Reports-Cleared: '&fВсі скарги успішно очищені'
    Args-Error: '&cНевідома команда.'
    No-Permission: '&cНема дозволу :('
    Reloaded: 'Коніфгурація успішно перезавантаженна'
    Reported-Format: '&c%player% &fwas reported by &a%reporter% &ffor &a%reason%&f.'
    Report-Submitted: '%prefix% &a%player% &fhas submitted a report. &8(&e/reports&8)'
    Click-To-Info: '&7(Click to open the Reports GUI)'
    Reports-Empty: '%prefix% &fSorry, but no reports have been submitted.'
    Specify-Reason: '&cВкажіть пичину вашої скарги.'
    Confirm: '&fPlease type &e/reports clear &fagain to confirm.'
    Cant-Report-Yourself: '&cВи не можете поскаржитися на самого себе.'
    Cant-Report-That-Player: 'Ви не можете поскаржитися на цього гравця.'
    Max-Reports-Reached: '&cЗабагато скарг'
    Nothing-To-Clear: ''
    Please-Wait: '&сВи маєте зачикати &c%cooldown%s&f.'
    Report-Usage: '&e/report [нікнейм] [причина]'
    Teleport-Message: 'Ви телепортувалися до %player%.'
    Player-Has-To-Be-Online: '&cВи не можете поскаржитися на %player% томущо нік зараз не онлайн'
    Claim-GUI-Not-Set-Up: '%prefix% &fSorry, but that player wasn''t rewarded as they''re offline and you haven''t set up the Reports ClaimGUI. &8(&e/reports setupclaimgui)'
    On-ClaimGUI-Open-Note: '%prefix% &fPlace the rewards you want players to receive for a completed report if they''re offline at the time of the reports completion.'
    Claim-GUI-Saved: '%prefix% &fThe &bClaim GUI &fhas been saved.'
    Report-Is-Already-Complete: '%prefix% &fSorry, but that report is already marked as &aComplete&f.'
    Report-Must-Be-Complete-To-Delete: '%prefix% &fSorry, but reports must be marked as ''&aComplete&f'' before deleting.'
    Nothing-To-Claim: '%prefix% &fSorry, but you have nothing to claim.'
    Report-Is-Not-Complete: ''
    Not-In-The-Image-Proof-URL-Whitelist: ''
    No-Image-Attached: ''
    Proof-Added: ''
    Added-URL-To-Whitelist: ''
    Canceled-Providing-Proof-Image: ''
    Your-Report-Was-Denied: '&cОдна з ваших скарг була відхилина.'
    Link-Format: '%prefix% &e%link%'
    Provide-Image-Proof:
    - '%prefix% &fPlease provide a link to an image of proof for your report in chat.'
    - '%prefix% &fYou can type ''cancel'' to cancel your report.'
    Player-Reported:
    - ''
    - '  &fВи успішно подали скаргу на &c%player%&f.'
    - '  &fПричина &3&l» &b%reason%&f.'
    - ''
    You-Have-Report-Rewards: '%prefix% &b&lHey! &fYou have been rewarded from a report! &e/reports claim'
settings:
    Inform-Operators: true
    Max-Reports-Per-Player: 99
    Command-Format: ' &3&l» &e%command% &3&l» &f%usage%'
    Require-Reported-Player-To-Be-Online: true
    Save-Reporters-Location: false
    Tell-Players-They-Have-Rewards-In-Their-ClaimGUI: true
    Perform-Commands-On-Report: false
    Commands-Upon-Reports:
    - 'adminchat %reporter% поскаржився на %reported% за:  %reason%'
    Use-Header-&-Footer: true
    Require-Image-Proof-Link-Before-Report-Creation: false
    Tell-Reporter-Their-Report-Was-Denied: true
    Open-Reports-GUI-Sound:
        Enabled: false
        Sound: BLOCK_CHEST_OPEN
    Open-Claim-GUI-Sound:
        Enabled: false
        Sound: BLOCK_CHEST_OPEN
    Clear-Reports-Timer: 3
    Submit-Report-Timer: 60
    # Timers are in seconds
    Reports-Must-Be-Confirmed-To-Delete: false
    Remove-Reports:
        Click-Type: RIGHT
    Change-Status:
        Click-Type: MIDDLE
    Open-Proof-Link:
        Click-Type: DROP
    Statuses:
        New: '&fНовий'
        WIP: '&eТреба перевірити'
        Complete: '&aГотовий'
    Give-Reporter-Rewards-On-Report-Complete:
        Enabled: true
        Reporter-Is-Online:
        - 'mail send %reporter% Дякуємо за те що ви допомагаєте нам модерувати AndriyCraft. Ми перевірили останню скаргу і ми забанили того на кого ви поскаржилися'
        Reporter-Is-Offline:
        - 'mail send %reporter% Дякуємо за те що ви допомагаєте нам модерувати AndriyCraft. Ми перевірили останню скаргу і ми забанили того на кого ви поскаржилися'
    Image-Proof-URL-Whitelist:
        - 'imgur.com'
        - 'i.imgur.com'
        - 'prntscr.com'
        - 'gyazo.com'
        - 'i.gyazo.com'
        - 'i.ibb.co'
        - 'ibb.co'
        - 'pasteboard.co'
sounds:
    Enabled: false
    Report-Submitted: ENTITY_PLAYER_LEVELUP
    Player-Reported-Notification: BLOCK_ANVIL_FALL
GUI:
    Name: '&cReports'
    Size: 54
    Default-Item:
        Player-Commands:
        - 'teleport %player%'
        Material: PAPER
        Name: '&a%reported%'
        Lore:
        - ''
        - ' &3&l» &fStatus &3&l» %status%'
        - ''
        - ' &3&l» &fSubmitted by &3&l» &b%reporter%'
        - ' &3&l» &fReported &3&l» &c%reported%'
        - ''
        - ' &3&l» &fReason &3&l» &b%reason%'
        - ''
        - '&7(Left-Click to teleport to %reported%)'
        - '&7(Right-Click to remove this Report)'
        - '&7(Middle-Click to update the report status)'
        - '&7(Drop to see if a proof image is attached)'
ClaimGUI:
    Name: '&bClaim GUI'
    Size: 27
    Players-View:
        Name: '&fYour Report Rewards'
        Size: 27
